NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('news/', include('news.urls')), # делаем так, чтобы все адреса из нашего приложения (news/urls.py)
    # сами автоматически подключались когда мы их добавим.
    path('', include('protect.urls')),
    path('sign/', include('sign.urls')),
    path('accounts/', include('allauth.urls')),
    path('rules/', TemplateView.as_view(template_name='news_app/rules_pages.html'), name='rules_page'),
    path('appointments/', include(('appointment.urls', 'appointments'), namespace='appointments')),
]

news/urls.py
from django.urls import path
from .views import NewsList, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, PostSearchView
from .views import subscribe_to_category, unsubscribe_from_category
from .views import AppointmentView
from .views import PostCategoryView
from .views import AllCategoriesView
from .views import view_log
from .views import errors_log
from .views import security_log
from .views import general_log
from .views import log_links




# импортируем наше представление
app_name = 'news'

urlpatterns = [
    # path — означает путь. В данном случае путь ко всем статьям у нас останется пустым, позже станет ясно почему
    path('', NewsList.as_view()),  # т.к. сам по себе это класс, то нам надо представить этот класс в виде view.
    # Для этого вызываем метод as_view
    path('<int:pk>/', PostDetailView.as_view(), name='post_detail'),  # Ссылка на детали статьи
    path('add/', PostCreateView.as_view(), name='post_create'),  # Ссылка на создание статьи
    path('edit/<int:pk>', PostUpdateView.as_view(), name='post_update'),  # Ссылка на редактирование статьи
    path('delete/<int:pk>', PostDeleteView.as_view(), name='post_delete'),  # Ссылка на удаление статьи
    path('search/', PostSearchView.as_view(), name='post_search'),  # Ссылка на поиск статьи
    path('make_app/', AppointmentView.as_view(), name='make_app'),
    path('all_categories/', AllCategoriesView.as_view(), name='all_categories'),
    path('category/<int:pk>', PostCategoryView.as_view(), name='category'), # Ссылка на категории
    path('subscribe/<int:pk>', subscribe_to_category, name='subscribe'), # Ссылка на подписчиков
    path('unsubscribe/<int:pk>', unsubscribe_from_category, name='unsubscribe'), # Ссылка на отписку
    path('log_links/', log_links, name='log_links'),
    path('view_log/', view_log, name='log_view'),
    path('general_log/', general_log, name='general_log'),
    path('errors_log/', errors_log, name='errors_log'),
    path('security_log/', security_log, name='security_log'),
]

news/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import User
from django.db.models import Sum
from django.contrib.sites.models import Site
from datetime import datetime
from django.contrib.auth.models import Group


# from django.core.validators import MinValueValidator


class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAuthor = models.SmallIntegerField(default=0)

    def update_rating(self):
        postRat = self.post_set.all().aggregate(postRating=Sum('rating'))
        pRat = 0
        pRat += postRat.get('postRating')

        commentRat = self.authorUser.comment_set.all().aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        self.ratingAuthor = pRat * 3 + cRat
        self.save()

    def __str__(self):
        return f'{self.authorUser}'


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)
    subscribers = models.ManyToManyField(User, related_name='subscribed_categories', blank=True)

    def __str__(self):
        return f'{self.name}'


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOICES = (
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья')
    )

    categoryType = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=ARTICLE)
    dateCreation = models.DateTimeField(auto_now_add=True)
    postCategory = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)

    # Методы like() и dislike() в моделях Comment и Post увеличивают/уменьшают рейтинг на единицу.
    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    # Метод preview() модели Post возвращает начало статьи (предварительный просмотр) длиной 124 символа
    # и добавляет многоточие в конце.
    def preview(self):
        return self.text[0:123] + '...'

    def __str__(self):
        return f'title: {self.title} || text: {self.text} || dateCreation: {self.dateCreation}'

    def get_absolute_url(self):  # добавим абсолютный путь, чтобы после создания нас перебрасывало на страницу с товаром
        return f'/news/{self.id}'


class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.categoryThrough}'


class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dateCreation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def __str__(self):
        return f'text: {self.text} || commentUser: {self.commentUser}'

    # Методы like() и dislike() в моделях Comment и Post увеличивают/уменьшают рейтинг на единицу.
    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()


class CustomSite(Site):
    is_active = models.BooleanField(default=True, verbose_name='Is Active')

    class Meta:
        verbose_name = 'Site'
        verbose_name_plural = 'Sites'

class CommonGroup(Group):
    class Meta:
        verbose_name = 'common'
        verbose_name_plural = 'common'

class Appointment(models.Model):
            date = models.DateField(
                default=datetime.utcnow,
            )
            client_name = models.CharField(
                max_length=200
            )
            message = models.TextField()

            def __str__(self):
                return f'{self.client_name}: {self.message}'


class Subscription(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'category')

news/forms.py
from django.forms import ModelForm, BooleanField  # Импортируем true-false поле
from .models import Post
from django import forms
from django.utils.safestring import mark_safe


# Создаём модельную форму
class PostForm(ModelForm):
    check_box = BooleanField(label='Согласен с правилами сайта', required=False)  # добавляем галочку или же true-false поле

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['check_box'].widget = forms.CheckboxInput(attrs={'type': 'checkbox'})
        self.fields['check_box'].label = mark_safe('Согласен с <a href="http://127.0.0.1:8000/news/rules.html">правилами сайта</a>')

    # в класс мета, как обычно, надо написать модель, по которой будет строиться форма и нужные нам поля.
    # Мы уже делали что-то похожее с фильтрами.
    class Meta:
        model = Post
        fields = ['title', 'text', 'postCategory', 'author']

news/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
# импоритируем необходимые дженерики
# импортируем класс ListView, который говорит нам о том, что в этом представлении мы будем выводить список объектов из БД
# импортируем класс DetailView получения деталей объекта
from django.core.paginator import Paginator  # импортируем класс, позволяющий удобно осуществлять постраничный вывод
from .models import Post, Category, Subscription, Author, PostCategory  # Дополнительно импортируем категорию, чтобы пользователь мог её выбрать
from .filters import PostFilter  # импортируем недавно написанный фильтр
from .forms import PostForm  # импортируем нашу форму
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.mail import send_mail, EmailMultiAlternatives
from datetime import datetime
from .models import Appointment
from django.urls import reverse_lazy, resolve
from django.template.loader import render_to_string
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.views.generic.base import View
from django.shortcuts import redirect
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator
import logging
from django.http import HttpResponse
import os


DEFAULT_FROM_EMAIL = settings.DEFAULT_FROM_EMAIL


logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)  # желаемый уровень логирования, например, DEBUG, INFO, ERROR.

# обработчик для записи логов в файл
log_file = 'view.log'
file_handler = logging.FileHandler(log_file)
file_handler.setLevel(logging.DEBUG)  # Установите уровень для файла

# форматтер для определения формата записей в лог-файле
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
file_handler.setFormatter(formatter)

# обработчик к логгеру
logger.addHandler(file_handler)

class NewsList(ListView):
    model = Post  # указываем модель, объекты которой мы будем выводить
    template_name = 'news.html'  # указываем имя шаблона, в котором будет лежать HTML,
    # в нём будут все инструкции о том, как именно пользователю должны вывестись наши объекты
    context_object_name = 'news'  # это имя списка, в котором будут лежать все объекты,
    # его надо указать, чтобы обратиться к самому списку объектов через HTML-шаблон
    ordering = [
        '-dateCreation']  # сортировка по дате публикации, сначала более новые /  queryset = Post.objects.order_by('-dateCreation')
    paginate_by = 10  # поставим постраничный вывод в один элемент


# дженерик для получения деталей о товаре
@method_decorator(cache_page(60*15), name='dispatch')
class PostDetailView(LoginRequiredMixin, DetailView):
    template_name = 'news_app/post_detail.html'
    queryset = Post.objects.all()


# дженерик для создания объекта. Надо указать только имя шаблона и класс формы который мы написали в прошлом юните.
# Остальное он сделает за вас
class PostCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'news_app/post_create.html'
    form_class = PostForm
    success_url = '/news/'
    permission_required = ('news.add_post',)


# дженерик для редактирования объекта
class PostUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'news_app/post_create.html'
    form_class = PostForm
    success_url = '/news/'
    permission_required = ('news.change_post',)

    # метод get_object мы используем вместо queryset, чтобы получить информацию об объекте который мы собираемся редактировать
    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        return Post.objects.get(pk=id)


# дженерик для удаления поста
class PostDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'news_app/post_delete.html'
    queryset = Post.objects.all()
    success_url = '/news/'
    permission_required = ('news.delete_post',)


# дженерик для поиска поста
class PostSearchView(ListView):
    model = Post
    template_name = 'news_app/post_search.html'
    context_object_name = 'news'  # это имя списка, в котором будут лежать все объекты,
    # его надо указать, чтобы обратиться к самому списку объектов через HTML-шаблон
    ordering = [
        '-dateCreation']  # сортировка по дате публикации, сначала более новые /  queryset = Post.objects.order_by('-dateCreation')

    def get_context_data(self, **kwargs):
        # забираем отфильтрованные объекты переопределяя метод get_context_data у наследуемого класса (привет, полиморфизм, мы скучали!!!)
        context = super().get_context_data(**kwargs)
        context['filter'] = PostFilter(self.request.GET,
                                       queryset=self.get_queryset())  # вписываем наш фильтр в контекст
        return context


class PostCategoryView(ListView):
    model = Post
    template_name = 'news_app/category.html'
    context_object_name = 'news'  # это имя списка, в котором будут лежать все объекты,
    # его надо указать, чтобы обратиться к самому списку объектов через HTML-шаблон
    ordering = ['-dateCreation']  # сортировка
    paginate_by = 10  # поставим постраничный вывод в один элемент

    def get_queryset(self):
        self.id = resolve(self.request.path_info).kwargs['pk']
        c = Category.objects.get(id=self.id)
        queryset = Post.objects.filter(postCategory=c)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        category = Category.objects.get(id=self.id)
        subscribed = category.subscribers.filter(email=user.email)
        if not subscribed:
            context['category'] = category


        return context

class AllCategoriesView(ListView):
    model = Category
    template_name = 'news_app/all_categories.html'
    context_object_name = 'categories'

    def get_queryset(self):
        return Category.objects.all()




@login_required
def subscribe_to_category(request, pk):  # подписка на категорию
    user = request.user
    category = Category.objects.get(id=pk)


    if not category.subscribers.filter(id=user.id).exists():
        category.subscribers.add(user)
        email = user.email
        html = render_to_string(
            'mail/subscribed.html',
            {
                'category': category,
                'user': user,
            },
        )
        msg = EmailMultiAlternatives(
            subject=f'Подписка на {category} на сайте News Paper',
            body='',
            from_email=DEFAULT_FROM_EMAIL,  # в settings.py
            to=[email, ],  # список получателей
        )
        msg.attach_alternative(html, 'text/html')

        try:
            msg.send()
        except Exception as e:
            print(e)
        return redirect(request.META.get('HTTP_REFERER'))
        # return redirect('news_list')
    return redirect(request.META.get('HTTP_REFERER'))  # возвращает на страницу, с кот-й поступил запрос


@login_required
def unsubscribe_from_category(request, pk):  # отписка от категории
    user = request.user
    c = Category.objects.get(id=pk)

    if c.subscribers.filter(id=user.id).exists():  # проверяем есть ли у нас такой подписчик
        c.subscribers.remove(user)  # то удаляем нашего пользователя
    # return redirect('http://127.0.0.1:8000/')
    return redirect(request.META.get('HTTP_REFERER'))


class AppointmentView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'news_app/make_app.html', {})

    def post(self, request, *args, **kwargs):
        appointment = Appointment(
            date=datetime.strptime(request.POST['date'], '%Y-%m-%d'),
            client_name=request.POST['client_name'],
            message=request.POST['message'],
        )
        appointment.save()

        return redirect('news:make_app')



def read_log_file(log_file):
    try:
        with open(log_file, 'r') as file:
            log_content = file.read()
    except FileNotFoundError:
        log_content = "Log file not found."
    return log_content

def view_log(request):
    log_content = read_log_file('view.log')
    return render(request, 'log_page_view.html', {'log_content': log_content})

def general_log(request):
    log_content = read_log_file('general.log')
    return render(request, 'log_page_general.html', {'log_content': log_content})

def errors_log(request):
    log_content = read_log_file('errors.log')
    return render(request, 'log_page_errors.html', {'log_content': log_content})

def security_log(request):
    log_content = read_log_file('security.log')
    return render(request, 'log_page_security.html', {'log_content': log_content})

def log_links(request):
    return render(request, 'log_page.html')

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block head_title %}{% endblock head_title %}</title>
    </head>
    <body>
        {% block body %}
            {% block content %}
            {% endblock content %}
        {% endblock body %}
        {% block extra_body %}
        {% endblock extra_body %}
    </body>
</html>

templates/log_page.html
<!DOCTYPE html>
<html>
<head>
    <title>Логирование</title>
</head>
<body>
    <h1>Содержимое лог-файла View.log</h1>
    <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'news:view_log' %}">Просмотреть View.log</a></li>
    <h1>Содержимое лог-файла Errors.log</h1>
    <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'news:errors_log' %}">Просмотреть Errors.log</a></li>
    <h1>Содержимое лог-файла General.log</h1>
    <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'news:general_log' %}">Просмотреть General.log</a></li>
    <h1>Содержимое лог-файла Security.log</h1>
    <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'news:security_log' %}">Просмотреть Security.log</a></li>
</body>
</html>

templates/log_page_errors.html
<!DOCTYPE html>
<html>
<head>
    <title>Логирование</title>
</head>
<body>
    <h1>Содержимое лог-файла Errors.log</h1>
    <pre>{{ log_content|linebreaksbr }}</pre>

</body>
</html>

templates/log_page_general.html
<!DOCTYPE html>
<html>
<head>
    <title>Логирование</title>
</head>
<body>
    <h1>Содержимое лог-файла General.log</h1>
    <pre>{{ log_content|linebreaksbr }}</pre>

</body>
</html>

templates/log_page_security.html
<!DOCTYPE html>
<html>
<head>
    <title>Логирование</title>
</head>
<body>
    <h1>Содержимое лог-файла Errors.log</h1>
    <pre>{{ log_content|linebreaksbr }}</pre>

</body>
</html>

templates/log_page_view.html
<!DOCTYPE html>
<html>
<head>
    <title>Логирование</title>
</head>
<body>
    <h1>Содержимое лог-файла View.log</h1>
    <pre>{{ log_content|linebreaksbr }}</pre>

</body>
</html>

templates/main.html
<html>
    <head>
        <title> Simple SignUp/SignIn app</title>
    </head>
    <body>
        <div>
            <h1><a href="/">Simple SignUp/SignIn app</a></h1>
        </div>
        {% block content %}
        {% endblock %}
    </body>
</html>

templates/news.html
<!--  наследуемся от шаблона default.html -->

{% extends 'flatpages/default.html' %} 
 
{% load custom_filters %} <!-- не забываем заранее загружать наши фильтры! -->

<!-- Название NEWS -->
{% block title %}
    Все новости
{% endblock title %}
 
<!-- В контенте на странице мы выводим саму статью, айди которой было передано в адрес -->
{% block content %}

    <br>
    <h3> Всего статей: {{ news|length }} </h3>
    <br>

    {% if news %} <!-- Выводим статьи только, если они есть, с помощью тега if -->

        <a href="{% url 'news:post_search' %}"> Поиск статьи </a>
        <br>
        <br>

        <table style="border-collapse: separate; border-spacing: 20px 0;">
            <tr>
                <td><strong>Заголовок</strong></td>
                <td></td>
                <td></td>
                <td><strong>Дата публикации</strong></td>
                <td><strong>Статья</strong></td>
            </tr>

            {% for post in news %} <!-- Для каждой статьи будет генерироваться новая строчка, т.е. новый html код. 
            При этом сам цикл работает точно так же, как и в python. 
            post — переменная цикла, т.е. наша статья, взятая из общего списка -->
                <tr>
                    <!-- не забываем, что переменные в шаблоне ничем не отличаются от переменных в python. 
                    Здесь так же можно получать доступ к полям класса. 
                    Например, здесь мы выводим имя, в следующем столбце описание, и т.д.  -->

                    <td class="text-start"> 
                        <a href="{% url 'news:post_detail' post.id %}"> {{ post.title|censor|truncatechars:30  }}</a>
                        <!-- При нажатии на заголовок статьи в таблице нас теперь будет перекидывать на страницу с информацией о товаре -->
                        <!-- используем собственый фильтр censor -->
                    </td>   

                    <td>
                        <a href="{% url 'news:post_update' post.id %}"><u>Редактировать</u></a>
                        <!-- добавим ссылку на редактирование товара-->
                    </td>

                    <td>
                        <a href="{% url 'news:post_delete' post.id %}"><u> Удалить </u></a>
                        <!-- добавим ссылку на удаление товара-->
                    </td>
                         
                    <td> {{ post.dateCreation|date:'d M Y' }} </td>
                    <!-- добавим ссылку на редактирование товара-->
                    
                    <td class="text-start"> {{ post.text|censor|truncatechars:50 }} </td> <!-- используем собственый фильтр censor и дописываем специальный фильтр, 
                    чтобы ограничить количество символов до 50. Все остальные символы превратятся в многоточие. -->
                </tr>
            {% endfor %}
        </table>

        {% else %} <!-- Если статей нет, то говорим что статей нет ;) -->
            <br>
            <h2>Статей нет!</h2>

    {% endif %}

    <br>
    <a href="{% url 'news:post_create' %}">Добавить новую статью</a> <br><br>

    <!-- Проверяем что поддерживается постраничный вывод -->
    {% if is_paginated %}
        
        <!-- Если доступна предыдущая страница, то даём ссылку на неё и самую первую страницу -->
        {% if page_obj.has_previous %}
            <a href="?page=1">First</a>
            <a href="?page={{ page_obj.previous_page_number }}"><<<</a>
        {% endif %}

        <!-- Показываем только текущую страницу и ближайшие к ней, чтобы список не тянулся и не захламлял страницу -->
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a>{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        <!-- Если есть следующая страница, то даём ссылку на неё и на самую последнюю страницу -->
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">>>></a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}

    {% endif %}

   
{% endblock content %}

templates/post.html
<!--  наследуемся от шаблона default.html -->
{% extends 'flatpages/default.html' %} 
 
{% load custom_filters %} <!-- не забываем заранее загружать наши фильтры! -->

<!-- Название у нас будет из заголовка -->
{% block title %}
    Статья "{{ post.title|censor }}"
{% endblock title %}
 
<!-- В контенте на странице мы выводим саму статью, айди которого было передано в адрес -->
{% block content %}
    <br>
    <h3>Статья: {{ post.title|censor }}</h3>
    <h6>Дата публикации: {{ post.dateCreation|date:'d M Y h:m' }}</h6>
    <br>
    {{ post.text|censor }}
{% endblock content %}