NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('news/', include('news.urls')), # делаем так, чтобы все адреса из нашего приложения (news/urls.py)
    # сами автоматически подключались когда мы их добавим.
    path('', include('protect.urls')),
    path('sign/', include('sign.urls')),
    path('accounts/', include('allauth.urls')),
    path('rules/', TemplateView.as_view(template_name='news_app/rules_pages.html'), name='rules_page'),
    path('appointments/', include(('appointment.urls', 'appointments'), namespace='appointments')),
]

news/urls.py
from django.urls import path
from .views import NewsList, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, PostSearchView
from .views import subscribe_to_category, unsubscribe_from_category
from .views import AppointmentView
from .views import PostCategoryView
from .views import AllCategoriesView
from .views import view_log
from .views import errors_log
from .views import security_log
from .views import general_log
from .views import log_links




# импортируем наше представление
app_name = 'news'

urlpatterns = [
    # path — означает путь. В данном случае путь ко всем статьям у нас останется пустым, позже станет ясно почему
    path('', NewsList.as_view()),  # т.к. сам по себе это класс, то нам надо представить этот класс в виде view.
    # Для этого вызываем метод as_view
    path('<int:pk>/', PostDetailView.as_view(), name='post_detail'),  # Ссылка на детали статьи
    path('add/', PostCreateView.as_view(), name='post_create'),  # Ссылка на создание статьи
    path('edit/<int:pk>', PostUpdateView.as_view(), name='post_update'),  # Ссылка на редактирование статьи
    path('delete/<int:pk>', PostDeleteView.as_view(), name='post_delete'),  # Ссылка на удаление статьи
    path('search/', PostSearchView.as_view(), name='post_search'),  # Ссылка на поиск статьи
    path('make_app/', AppointmentView.as_view(), name='make_app'),
    path('all_categories/', AllCategoriesView.as_view(), name='all_categories'),
    path('category/<int:pk>', PostCategoryView.as_view(), name='category'), # Ссылка на категории
    path('subscribe/<int:pk>', subscribe_to_category, name='subscribe'), # Ссылка на подписчиков
    path('unsubscribe/<int:pk>', unsubscribe_from_category, name='unsubscribe'), # Ссылка на отписку
    path('log_links/', log_links, name='log_links'),
    path('view_log/', view_log, name='log_view'),
    path('general_log/', general_log, name='general_log'),
    path('errors_log/', errors_log, name='errors_log'),
    path('security_log/', security_log, name='security_log'),
]

templates/news_app/all_categories.html
{% extends 'flatpages/default.html' %}

{% block title %} All Categories {% endblock title %}

{% block content %}
    <h3>All Categories</h3>
    <ul>
        {% for category in categories %}
            <li><a href="{% url 'news:category' category.id %}">{{ category.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}

templates/news_app/category.html
<!--  наследуемся от шаблона default.html -->
{% extends 'flatpages/default.html' %}

{% load custom_filters %} <!-- не забываем заранее загружать наши фильтры! -->

<!-- Название у нас будет из заголовка -->
{% block title %} Categories {% endblock title %}

{% block content %}
    <br>
    <div>
    {% if category.id %}
        <h3>Подписаться на категорию <strong>{{ category.name }}?</strong></h3>
        <h4><button> <a href="{% url 'news:subscribe' category.id %}"> Подписаться </a></button></h4>
    <hr>
    {% endif %}
    </div>
    {% include 'news_app/inc/posts.html' %}

    <hr>
    <br>
    <h5><a href="/news/"> <--Вернуться к новостям </a></h5>
    <br>


{% endblock content %}

templates/news_app/make_app.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Проверка задач</title>
</head>

<body>
    <h1>Проверка задач</h1>
    <form action="{% url 'news:make_app' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="client_name">Имя</label>
        <input type="text" name="client_name"><br>
        <label for="message">Описание</label>
        <input type="text" name="message"><br>
        <label for="date">Время</label>
        <input type="date" name="date">.<br>
        <input type="submit">
    </form>

    <br>
    <a href="/news/"> <--Вернуться к новостям </a>
</body>

</html>

templates/news_app/post_create.html
<!--  наследуемся от шаблона default.html -->
{% extends 'flatpages/default.html' %} 
 
{% load custom_filters %} <!-- не забываем заранее загружать наши фильтры! -->

<!-- Название у нас будет из заголовка -->
{% block title %}
    Создание/редактирование статьи
{% endblock title %}

{% block content %}
    <br>
    <h4>Заполните все поля для создания/редактирования статьи</h4>
    <br>
    <form method="POST" style="display: flex; flex-wrap: wrap; align-items: flex-start; margin: 0 10px;">
        {% csrf_token %} 
        {{ form }} <!-- Теперь нам нужна только готовая форма и кнопка -->
        <input type="submit" value="Добавить статью">
    </form>
    <br>
    <a href="/news/"> <--Вернуться к новостям </a>
{% endblock content %}

templates/news_app/post_delete.html
<!--  наследуемся от шаблона default.html -->
{% extends 'flatpages/default.html' %} 
 
{% load custom_filters %} <!-- не забываем заранее загружать наши фильтры! -->

<!-- Название у нас будет из заголовка -->
{% block title %}
    Удаление статьи "{{ post.title|censor }}"
{% endblock title %}
 
<!-- В контенте на странице мы выводим саму статью, айди которого было передано в адрес -->
{% block content %}
    <br>
    <h2>Вы действительно хотите удалить данный пост?</h2>
    <br>
    <table style="border-collapse: separate; border-spacing: 20px 0;">
        <thead>
            <th> Заголовок </th>
            <th> Дата публикации </th>
            <th> Статья </th>
            <th> Автор </th>
        </thead>
        <tr>
            <td> {{ post.title|censor }} </td>
            <td> {{ post.dateCreation|date:'d M Y h:m' }} </td>
            <td> {{ post.text|censor }} </td>
            <td> {{ post.author }} </td>
        </tr>
    </table>
    <br>    
    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="Подтвердить">
    </form>
    <br>
    <a href="/news/"> <--Вернуться к новостям </a>
{% endblock content %}

templates/news_app/post_detail.html
<!--  наследуемся от шаблона default.html -->
{% extends 'flatpages/default.html' %} 
 
{% load custom_filters %} <!-- не забываем заранее загружать наши фильтры! -->

<!-- Название у нас будет из заголовка -->
{% block title %}
    Статья "{{ post.title|censor }}"
{% endblock title %}
 
<!-- В контенте на странице мы выводим саму статью, айди которого было передано в адрес -->
{% block content %}

    <br>
    <h3>Статья: "{{ post.title|censor }}"</h3><br>
    <h6>Дата публикации: {{ post.dateCreation|date:'d M Y h:m' }}</h6>
    <h6>Автор: {{ post.author }}</h6>
    <br>
    {{ post.text|censor }}
    <br>
    <br>
    <a href="/news/"> <--Вернуться к новостям </a>
{% endblock content %}

templates/news_app/post_search.html
<!--  наследуемся от шаблона default.html -->
{% extends 'flatpages/default.html' %} 
 
{% load custom_filters %} <!-- не забываем заранее загружать наши фильтры! -->

<!-- Название у нас будет из заголовка -->
{% block title %}
    Поиск статьи
{% endblock title %}
 
<!-- В контенте на странице мы выводим саму статью, айди которого было передано в адрес -->
{% block content %}
    <br>
    
    {% if news %} <!-- Выводим статьи только, если они есть, с помощью тега if -->

        <!-- Перед таблицей добавим форму для поиска -->
        <form method="GET">
            {{ filter.form }} <!-- Форму от фильтров за нас сделает Django. А вот кнопку, увы, придётся делать самому -->
            <input type="submit" value="Найти">
            <br><br>
            <a href="{% url 'post_search' %}">Сбросить фильтр</a>
        </form> 
        
        <br>

        <h3>Всего найдено статей:  {{ filter.qs|length }} </h3>
        <br>

        <table style="border-collapse: separate; border-spacing: 20px 0;">
            <thead>
                <th> Заголовок </th>
                <th></th>
                <th></th>
                <th> Дата публикации </th>
                <th> Статья </th>
                <th> Автор </th>
            </thead>

            {% for post in filter.qs %} <!-- поменяем news на filter.qs, т.к. теперь мы забираем уже отобранную по каким-то параметрам информацию -->
            <!-- Для каждой статьи будет генерироваться новая строчка, 
            т.е. новый html код. При этом сам цикл работает точно так же, как и в python. 
            post — переменная цикла, т.е. наша статья, взятая из общего списка -->

                <tr>
                    <td class="text-start"> 
                        <a href="{% url 'news:post_detail' post.id %}"> {{ post.title|censor|truncatechars:30 }}</a>
                        <!-- При нажатии на заголовок статьи в таблице нас теперь будет перекидывать на страницу с информацией о товаре -->
                        <!-- используем собственый фильтр censor -->
                    </td>
                    
                    <td>        
                        <a href="{% url 'news:post_update' post.id %}"><u>Редактировать</u></a>
                        <!-- добавим ссылку на редактирование товара-->
                    </td>
                    
                    <td>
                        <a href="{% url 'news:post_delete' post.id %}"><u> Удалить </u></a>
                        <!-- добавим ссылку на удаление товара-->
                    </td> 

                    <td> {{ post.dateCreation|date:'d M Y h:m' }} </td>
                    
                    <td class="text-start"> {{ post.text|censor|truncatechars:50 }} </td> <!-- используем собственый фильтр censor и дописываем специальный фильтр, 
                        чтобы ограничить количество символов до 50. Все остальные символы превратятся в многоточие. -->

                    <td> {{ post.author }} </td>
                </tr>
            {% endfor %}
        </table>
        
        {% else %} <!-- Если статей нет, то говорим что статей нет ;) -->
            <br>
            <h2>Статей нет!</h2>

    {% endif %}
    
    <!-- Проверяем что поддерживается постраничный вывод -->
    {% if is_paginated %}
        
        <!-- Если доступна предыдущая страница, то даём ссылку на неё и самую первую страницу -->
        {% if page_obj.has_previous %}
            <a href="?page=1">First</a>
            <a href="?page={{ page_obj.previous_page_number }}"><<<</a>
        {% endif %}

        <!-- Показываем только текущую страницу и ближайшие к ней, чтобы список не тянулся и не захламлял страницу -->
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a>{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        <!-- Если есть следующая страница, то даём ссылку на неё и на самую последнюю страницу -->
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">>>></a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}

    {% endif %}

    <br>
    <a href="/news/"> <--Вернуться к новостям </a>

{% endblock content %}

templates/news_app/rules_pages.html
<!--  наследуемся от шаблона default.html -->
{% extends 'flatpages/default.html' %}

<!--   не забываем заранее загружать наши фильтры! -->

<!-- Название NEWS -->
{% block title %}
    Задание модуля D5
{% endblock title %}

{% block content %}
    <div style="text-align: left; margin-left: auto;">
        <br>
        <h3>Правила:</h3>
        <hr>
        <ol>
            <li>НЕ ОЗОРНИЧАТЬ и НЕ МАТЕРИТЬСЯ</li>

        </ol>
        <hr>
    </div>

{% endblock content %}